### ISSUE TITLE
Error in validation

### ISSUE THREAD

**Issue by jovelangella** [kennethlaqui/harem-appointment-backend#1]
Why return the valid data as error?

**Comment by kennethlaqui** [comment]
where?

**Comment by jovelangella** [comment]
[https://github.com/kennethlaqui/harem-appointment-backend/commit/9d6ff60181726cb6691364f76affe2099965656f#r46459974](url)

**Comment by kennethlaqui** [comment]
Fixed! Thank you @jovelangella!
